# Generated by Django 5.1.3 on 2024-11-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
