# Generated by Django 5.1.3 on 2024-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroup',
            name='num_members',
            field=models.IntegerField(default=0),
        ),
    ]
