# Generated by Django 5.1.3 on 2024-11-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_messagegroup_num_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroup',
            name='num_members',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
