# Generated by Django 5.1.3 on 2024-11-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_user_appuser_alter_message_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='pasword',
            new_name='password',
        ),
    ]
